### ISSUE TITLE
MSP crashers from go-fuzz

### ISSUE THREAD

**Issue by andrewbuss** [cloudflare/redoctober#110]
Go-fuzz found that "(),)" crashes StringToMSP. I might try to debug this later today, but I'll add an issue in case I don't get the chance.

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x458130]
    
    goroutine 1 [running]:
    github.com/cloudflare/redoctober/msp.StringToFormatted(0xc82000a663, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/go-fuzz-build967867540/src/github.com/cloudflare/redoctober/msp/formatted.go:72 +0x1150
    github.com/cloudflare/redoctober/msp.StringToMSP(0xc82000a660, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/go-fuzz-build967867540/src/github.com/cloudflare/redoctober/msp/msp.go:108 +0x314
    github.com/cloudflare/redoctober/msp.Fuzz(0x7fb3a13cf000, 0x4, 0x200000, 0x3)
        /tmp/go-fuzz-build967867540/src/github.com/cloudflare/redoctober/msp/msp_fuzz.go:4 +0x8f
    github.com/dvyukov/go-fuzz/go-fuzz-dep.Main(0x5f77c0)
        /home/andrew/go/src/github.com/dvyukov/go-fuzz/go-fuzz-dep/main.go:47 +0x14c
    main.main()
        /tmp/go-fuzz-build967867540/src/go-fuzz-main/main.go:10 +0x23
    exit status 2

**Comment by Bren2010** [comment]
Thank you for finding this!

Don't worry about fixing it--I'll work on the parsers some this morning and open a PR later today.

**Comment by andrewbuss** [comment]
Closing; this was fixed by #111 

Go-fuzz didn't find anything else with the new StringToMSP after ~250M runs.
