### ISSUE TITLE
Allow permanent delegates

### ISSUE THREAD

**Issue by mrjonny2** [cloudflare/redoctober#146]
Is there a way to add a delegate to a vault so that they are there permanently?

**Comment by kisom** [comment]
There isn't, no. A user can do a long-term delegation, but not permanent.

**Comment by mrjonny2** [comment]
Would it then be possible to create an alert to a web hook when a delegation expires?

**Comment by kisom** [comment]
There is no communication right now between redoctober and any external
services besides hipchat right now. At some point in the future, support
may be added but it's not something we've prioritised working on right now.
