### ISSUE TITLE
Allow multiple delegations per user

### ISSUE THREAD

**Issue by grittygrease** [cloudflare/redoctober#82]
A user should be able to create multiple non-overlapping delegations. For example, it should be valid to delegate 1 decryption for label foo for 1 minute at the same time as 10 decryptions for label bar for 10 hours, and have these expire independently.

This can be achieved in a backwards-compatible way by creating the concept of a labeled delegation "slot". The current delegations will be given the "default" slot. When creating a delegation, an additional slot parameter should be permitted. Every new delegation should replace the current delegation for a given slot.

**Comment by grittygrease** [comment]
@ejcx, you're taking this, right?

**Comment by ejcx** [comment]
yup

**Comment by ejcx** [comment]
Merged into master here in [c0932d9](https://github.com/cloudflare/redoctober/commit/c0932d9cb5439e684f5420b0f30c51d943ca452f)
